import { contextBridge, ipcRenderer } from 'electron'
import type { SpeakSubApi } from '../shared/types'

function onIpc<T>(channel: string, listener: (payload: T) => void): () => void {
  const handler = (_: Electron.IpcRendererEvent, payload: T) => listener(payload)
  ipcRenderer.on(channel, handler)
  return () => ipcRenderer.removeListener(channel, handler)
}

const api: SpeakSubApi = {
  getAppVersion: () => ipcRenderer.invoke('app:version'),
  parseTopicDocument: (fileName, data) => ipcRenderer.invoke('practice:parse-topic-document', fileName, data),
  startPractice: (topic, level, strength, source, mode, focus, prompt, systemPrompt, topicDocument) => ipcRenderer.invoke('practice:start', topic, level, strength, source, mode, focus, prompt, systemPrompt, topicDocument),
  getPromptTemplates: () => ipcRenderer.invoke('practice:templates:get'),
  savePromptTemplates: (templates) => ipcRenderer.invoke('practice:templates:save', templates),
  getPracticePreferences: () => ipcRenderer.invoke('practice:preferences:get'),
  savePracticePreferences: (preferences) => ipcRenderer.invoke('practice:preferences:save', preferences),
  sendPracticeMessage: (message, speakReply) => ipcRenderer.invoke('practice:sendMessage', message, speakReply),
  sendApiMessage: (message) => ipcRenderer.invoke('api:sendMessage', message),
  startVoiceCapture: () => ipcRenderer.invoke('voice:capture:start'),
  stopVoiceCapture: () => ipcRenderer.invoke('voice:capture:stop'),
  reportVoiceCaptureStatus: (status) => ipcRenderer.invoke('voice:capture:status', status),
  sendVoiceAudio: (chunk) => ipcRenderer.invoke('voice:audio', chunk),
  notifyVoicePlaybackEnded: (chunkId) => ipcRenderer.invoke('voice:playback:ended', chunkId),
  getSpeechAssetState: () => ipcRenderer.invoke('speech-assets:get'),
  getSpeechAssetInstallInfo: () => ipcRenderer.invoke('speech-assets:install-info'),
  openSpeechAssetDirectory: () => ipcRenderer.invoke('speech-assets:open-directory'),
  downloadSpeechAssets: (includeTts) => ipcRenderer.invoke('speech-assets:download', includeTts),
  removeKokoroModel: () => ipcRenderer.invoke('speech-assets:remove-kokoro'),
  endPractice: () => ipcRenderer.invoke('practice:end'),
  cancelPracticeStart: () => ipcRenderer.invoke('practice:cancel-start'),
  getState: () => ipcRenderer.invoke('app:state'),
  completeConnection: () => ipcRenderer.invoke('connection:complete'),
  clearWebConnectionLogin: () => ipcRenderer.invoke('connection:clear-web-login'),
  reloadWebConnectionPage: () => ipcRenderer.invoke('connection:reload'),
  importWebConnectionLogin: () => ipcRenderer.invoke('connection:import-browser-login'),
  showConnectionPage: () => ipcRenderer.invoke('connection:show'),
  clearPendingCleanup: () => ipcRenderer.invoke('connection:clear-pending-cleanup'),
  hideConnectionPage: () => ipcRenderer.invoke('connection:hide'),
  minimizeWindow: () => ipcRenderer.invoke('window:minimize'),
  toggleMaximizeWindow: () => ipcRenderer.invoke('window:toggle-maximize'),
  closeWindow: () => ipcRenderer.invoke('window:close'),
  updateSubtitle: (settings) => ipcRenderer.invoke('subtitle:update', settings),
  toggleOverlay: () => ipcRenderer.invoke('subtitle:toggle'),
  setOverlayInteractive: (interactive) => ipcRenderer.invoke('subtitle:interactive', interactive),
  moveOverlay: (origin, deltaX, deltaY) => ipcRenderer.invoke('subtitle:move', origin, deltaX, deltaY),
  resizeOverlay: (direction, origin, deltaX, deltaY) => ipcRenderer.invoke('subtitle:resize', direction, origin, deltaX, deltaY),
  lookup: (selection, sentence) => ipcRenderer.invoke('learning:lookup', selection, sentence),
  saveSessionFavorite: (word) => ipcRenderer.invoke('session:save-favorite', word),
  saveSessionSentence: (sourceMessageId) => ipcRenderer.invoke('session:save-sentence', sourceMessageId),
  searchSessions: (query) => ipcRenderer.invoke('learning:sessions:search', query),
  getSessionDetail: (id) => ipcRenderer.invoke('learning:sessions:get', id),
  regenerateSessionReview: (id) => ipcRenderer.invoke('learning:sessions:review', id),
  deleteSession: (id) => ipcRenderer.invoke('learning:sessions:delete', id),
  listVocabulary: (filter) => ipcRenderer.invoke('learning:vocabulary:list', filter),
  listSavedSentences: (filter) => ipcRenderer.invoke('learning:sentences:list', filter),
  updateSavedSentenceStatus: (id, learningStatus) => ipcRenderer.invoke('learning:sentences:update-status', id, learningStatus),
  updateVocabularyFamiliarity: (id, familiarity) => ipcRenderer.invoke('learning:vocabulary:update', id, familiarity),
  reviewVocabulary: (id, rating) => ipcRenderer.invoke('learning:vocabulary:review', id, rating),
  getReviewQueue: () => ipcRenderer.invoke('learning:vocabulary:queue'),
  getLearningDashboard: (period) => ipcRenderer.invoke('learning:dashboard', period),
  createNextPracticeDraft: (sessionId) => ipcRenderer.invoke('learning:next-practice', sessionId),
  getArchiveDirectory: () => ipcRenderer.invoke('archive:get-directory'),
  chooseArchiveDirectory: () => ipcRenderer.invoke('archive:choose-directory'),
  copyCommunityGroupNumber: () => ipcRenderer.invoke('community:copy-qq-group-number'),
  getProviderSettings: () => ipcRenderer.invoke('providers:get'),
  saveProviderSettings: (settings) => ipcRenderer.invoke('providers:save', settings),
  discoverProviderModels: (input) => ipcRenderer.invoke('providers:models', input),
  checkLlmConnection: (input) => ipcRenderer.invoke('providers:check-llm', input),
  checkAliyunConnection: (input) => ipcRenderer.invoke('providers:check-aliyun', input),
  previewMimoTtsVoice: (input) => ipcRenderer.invoke('providers:preview-mimo-tts', input),
  cancelMimoTtsPreview: () => ipcRenderer.invoke('providers:cancel-mimo-preview'),
  saveMicrophoneShortcut: (shortcut) => ipcRenderer.invoke('microphone:shortcut:save', shortcut),
  toggleMicrophoneGate: () => ipcRenderer.invoke('microphone:toggle'),
  setMicrophoneGate: (active) => ipcRenderer.invoke('microphone:set', active),
  clearAllData: () => ipcRenderer.invoke('data:clear'),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  downloadAndInstallUpdate: () => ipcRenderer.invoke('update:download-and-install'),
  openUpdateRelease: () => ipcRenderer.invoke('update:open-release'),
  onTranscript: (listener) => onIpc('transcript:event', listener),
  onSubtitleSettings: (listener) => onIpc('subtitle:settings', listener),
  onAutomationStatus: (listener) => onIpc('automation:status', listener),
  onPracticeEnded: (listener) => onIpc('practice:ended', listener),
  onConnectionState: (listener) => onIpc('connection:state', listener),
  onVoiceAudio: (listener) => onIpc('voice:audio', listener),
  onSpeechAssetState: (listener) => onIpc('speech-assets:state', listener),
  onSpeechUsage: (listener) => onIpc('speech:usage', listener),
  onVoicePhase: (listener) => onIpc('voice:phase', listener),
  onVoiceInterrupt: (listener) => onIpc('voice:interrupt', listener),
  onMicrophoneGateState: (listener) => onIpc('microphone:state', listener),
  onUpdateProgress: (listener) => onIpc('update:progress', listener)
}

contextBridge.exposeInMainWorld('speaksub', api)
