import { contextBridge, ipcRenderer } from 'electron'
import type { SpeakSubApi } from '../shared/types'

const api: SpeakSubApi = {
  startPractice: (topic, level, strength, source, mode, focus) => ipcRenderer.invoke('practice:start', topic, level, strength, source, mode, focus),
  sendPracticeMessage: (message) => ipcRenderer.invoke('practice:sendMessage', message),
  sendApiMessage: (message) => ipcRenderer.invoke('api:sendMessage', message),
  startVoiceCapture: () => ipcRenderer.invoke('voice:capture:start'),
  stopVoiceCapture: () => ipcRenderer.invoke('voice:capture:stop'),
  sendVoiceAudio: (chunk) => ipcRenderer.invoke('voice:audio', chunk),
  notifyVoicePlaybackEnded: (chunkId) => ipcRenderer.invoke('voice:playback:ended', chunkId),
  getSpeechAssetState: () => ipcRenderer.invoke('speech-assets:get'),
  downloadSpeechAssets: () => ipcRenderer.invoke('speech-assets:download'),
  endPractice: () => ipcRenderer.invoke('practice:end'),
  cancelPracticeStart: () => ipcRenderer.invoke('practice:cancel-start'),
  getState: () => ipcRenderer.invoke('app:state'),
  completeConnection: () => ipcRenderer.invoke('connection:complete'),
  showConnectionPage: () => ipcRenderer.invoke('connection:show'),
  clearPendingCleanup: () => ipcRenderer.invoke('connection:clear-pending-cleanup'),
  hideConnectionPage: () => ipcRenderer.invoke('connection:hide'),
  updateSubtitle: (settings) => ipcRenderer.invoke('subtitle:update', settings),
  toggleOverlay: () => ipcRenderer.invoke('subtitle:toggle'),
  setOverlayInteractive: (interactive) => ipcRenderer.invoke('subtitle:interactive', interactive),
  resizeOverlay: (direction, origin, deltaX, deltaY) => ipcRenderer.invoke('subtitle:resize', direction, origin, deltaX, deltaY),
  lookup: (selection, sentence) => ipcRenderer.invoke('learning:lookup', selection, sentence),
  saveSessionFavorite: (word) => ipcRenderer.invoke('session:save-favorite', word),
  searchSessions: (query) => ipcRenderer.invoke('learning:sessions:search', query),
  getSessionDetail: (id) => ipcRenderer.invoke('learning:sessions:get', id),
  deleteSession: (id) => ipcRenderer.invoke('learning:sessions:delete', id),
  listVocabulary: (filter) => ipcRenderer.invoke('learning:vocabulary:list', filter),
  updateVocabularyFamiliarity: (id, familiarity) => ipcRenderer.invoke('learning:vocabulary:update', id, familiarity),
  getReviewQueue: () => ipcRenderer.invoke('learning:vocabulary:queue'),
  getLearningDashboard: (period) => ipcRenderer.invoke('learning:dashboard', period),
  createNextPracticeDraft: (sessionId) => ipcRenderer.invoke('learning:next-practice', sessionId),
  getArchiveDirectory: () => ipcRenderer.invoke('archive:get-directory'),
  chooseArchiveDirectory: () => ipcRenderer.invoke('archive:choose-directory'),
  getProviderSettings: () => ipcRenderer.invoke('providers:get'),
  saveProviderSettings: (settings) => ipcRenderer.invoke('providers:save', settings),
  saveMicrophoneShortcut: (shortcut) => ipcRenderer.invoke('microphone:shortcut:save', shortcut),
  toggleMicrophoneGate: () => ipcRenderer.invoke('microphone:toggle'),
  setMicrophoneGate: (active) => ipcRenderer.invoke('microphone:set', active),
  clearAllData: () => ipcRenderer.invoke('data:clear'),
  onTranscript: (listener) => { const handler = (_: Electron.IpcRendererEvent, event: Parameters<typeof listener>[0]) => listener(event); ipcRenderer.on('transcript:event', handler); return () => ipcRenderer.removeListener('transcript:event', handler) },
  onSubtitleSettings: (listener) => { const handler = (_: Electron.IpcRendererEvent, settings: Parameters<typeof listener>[0]) => listener(settings); ipcRenderer.on('subtitle:settings', handler); return () => ipcRenderer.removeListener('subtitle:settings', handler) },
  onAutomationStatus: (listener) => { const handler = (_: Electron.IpcRendererEvent, status: Parameters<typeof listener>[0]) => listener(status); ipcRenderer.on('automation:status', handler); return () => ipcRenderer.removeListener('automation:status', handler) },
  onPracticeEnded: (listener) => { const handler = (_: Electron.IpcRendererEvent, result: Parameters<typeof listener>[0]) => listener(result); ipcRenderer.on('practice:ended', handler); return () => ipcRenderer.removeListener('practice:ended', handler) },
  onConnectionState: (listener) => { const handler = (_: Electron.IpcRendererEvent, state: Parameters<typeof listener>[0]) => listener(state); ipcRenderer.on('connection:state', handler); return () => ipcRenderer.removeListener('connection:state', handler) },
  onVoiceAudio: (listener) => { const handler = (_: Electron.IpcRendererEvent, chunk: Parameters<typeof listener>[0]) => listener(chunk); ipcRenderer.on('voice:audio', handler); return () => ipcRenderer.removeListener('voice:audio', handler) },
  onSpeechAssetState: (listener) => { const handler = (_: Electron.IpcRendererEvent, state: Parameters<typeof listener>[0]) => listener(state); ipcRenderer.on('speech-assets:state', handler); return () => ipcRenderer.removeListener('speech-assets:state', handler) },
  onVoicePhase: (listener) => { const handler = (_: Electron.IpcRendererEvent, phase: Parameters<typeof listener>[0]) => listener(phase); ipcRenderer.on('voice:phase', handler); return () => ipcRenderer.removeListener('voice:phase', handler) },
  onVoiceInterrupt: (listener) => { const handler = () => listener(); ipcRenderer.on('voice:interrupt', handler); return () => ipcRenderer.removeListener('voice:interrupt', handler) },
  onMicrophoneGateState: (listener) => { const handler = (_: Electron.IpcRendererEvent, state: Parameters<typeof listener>[0]) => listener(state); ipcRenderer.on('microphone:state', handler); return () => ipcRenderer.removeListener('microphone:state', handler) }
}

contextBridge.exposeInMainWorld('speaksub', api)
